[project]
authors = ["Juraj Mičko <micko.juraj64@gmail.com>"]
channels = ["conda-forge"]
name = "zurich-feiertage-ics"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
generate-ics = "python main.py"

[dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"
polars = ">=1.0.0,<2"
icalendar = ">=6.3.2,<7"
